server:
  port: 8080
  address: 0.0.0.0
spring:
  application:
    name: "basicUserInfo"
  devtools:
    add-properties: false
  main:
    web-application-type: "reactive"
  webflux:
    base-path: "/api/v1/comII/"
logging:
  level:
    root: "info"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
postgresql:
  host: "http://192.168.30.30"
  dbname: "midb"
  username: "admin"
  password: "admin123"
  port: 5432